### Health
GET http://localhost:3000/health

### Get all bookmarks
GET http://localhost:3000/api/bookmarks

### Get one bookmark
GET http://localhost:3000/api/bookmarks/1

### Create bookmark
POST http://localhost:3000/api/bookmarks
content-type: application/json

{
  "url": "https://docs.rs",
  "title": "Docs.rs",
  "description": "Rust docs"
}

### Create bookmark minimal
POST http://localhost:3000/api/bookmarks
content-type: application/json

{
  "url": "https://docs.rs"
}

### Update bookmark
PUT http://localhost:3000/api/bookmarks/1
content-type: application/json

{
  "url": "https://gogole.com",
  "title": "Google",
  "description": "Google search engine"
}

### Delete bookmark
DELETE http://localhost:3000/api/bookmarks/1

### Get URL info
GET http://localhost:3000/api/urls/http%3A%2F%2Fdocs.rs