### Get all bookmarks
GET http://localhost:3000/bookmarks

### Get one bookmark
GET http://localhost:3000/bookmarks/4

### Create bookmark
POST http://localhost:3000/bookmarks
content-type: application/json

{
  "url": "https://docs.rs",
  "description": "Rust docs"
}

### Create bookmark without description
POST http://localhost:3000/bookmarks
content-type: application/json

{
  "url": "https://docs.rs"
}

### Update bookmark
PUT http://localhost:3000/bookmarks/1
content-type: application/json

{
  "url": "https://gogole.com",
  "description": "Google search engine"
}

### Delete bookmark
DELETE http://localhost:3000/bookmarks/2
