FROM ubuntu:22.04

RUN apt-get update ; \
    apt-get install -y tini ca-certificates ; \
    apt-get clean ; \
    rm -rf /var/lib/apt/lists/*

COPY target /usr/local/bin/

EXPOSE 3000

WORKDIR /usr/local/bin
CMD [ "/usr/bin/tini", "backend" ]