[package]
name = "common"
version.workspace = true
edition = "2021"
publish = false
repository = "https://github.com/cpollet/rbm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.8.1"

[features]
