name: Build release

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - gh-actions

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'
      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1
        with:
          version: 'latest'
      - name: cache build
        uses: Swatinem/rust-cache@v2
      - name: Build release
        run: cargo make build-release
      - name: Save backend binary
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: target/release/backend
          retention-days: 1
          if-no-files-found: error
  build-docker:
    name: Create docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch backend binary
        uses: actions/download-artifact@v3
        with:
          name: backend
          path: docker/target
      - name: Make backend executable
        run: chmod a+x docker/target/backend
      - name: Create docker image
        working-directory: ./docker
        run: docker build --file Dockerfile --tag shaarlot:latest --tag shaarlot:$(date +%s) .

# todo: webhook to trigger redeploy on staging.shaarlot.net
# todo: manual workflow to trigger deployment on live.shaarlot.net & demo.shaarlot.net