//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::account::Entity as Account;
pub use super::bookmark::Entity as Bookmark;
pub use super::password_recovery::Entity as PasswordRecovery;
